import { TeamMember, ServiceOffering, Testimonial, NavLink } from "./types";

export const NAVIGATION_LINKS: NavLink[] = [
  { name: "Home", href: "#home" },
  { name: "Studio", href: "#studio" },
  { name: "Services", href: "#services" },
  { name: "Contact", href: "#contact" },
  { name: "FAQ's", href: "#faqs" },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "team-1",
    name: "Alex",
    role: "Strategist",
    image: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-24 h-24 md:w-28 md:h-28 lg:w-32 lg:h-32",
    positionClass: "left-[5%] bottom-[5%] lg:bottom-[8%]",
    animationDelay: 0.1,
  },
  {
    id: "team-2",
    name: "Benjamin",
    role: "Creative Director",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-20.5 h-20.5 md:w-24 md:h-24 lg:w-28 lg:h-28",
    positionClass: "left-[14%] bottom-[15%] lg:bottom-[20%]",
    animationDelay: 0.2,
  },
  {
    id: "team-3",
    name: "Sophia",
    role: "Lead Designer",
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-24 h-24 md:w-28 md:h-28 lg:w-34 lg:h-34",
    positionClass: "left-[26%] bottom-[28%] lg:bottom-[34%]",
    animationDelay: 0.3,
  },
  {
    id: "team-4",
    name: "Tariq",
    role: "UX Researcher",
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-26 h-26 md:w-30 md:h-30 lg:w-36 lg:h-36",
    positionClass: "left-[31%] bottom-[2%] lg:bottom-[4%]",
    animationDelay: 0.4,
  },
  {
    id: "team-5",
    name: "Oliver",
    role: "Brand Director",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-24 h-24 md:w-28 md:h-28 lg:w-34 lg:h-34",
    positionClass: "left-[48%] bottom-[18%] lg:bottom-[24%]",
    animationDelay: 0.5,
  },
  {
    id: "team-6",
    name: "Leo",
    role: "Digital Architect",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-22 w-22 md:w-26 md:h-26 lg:w-32 lg:h-32",
    positionClass: "left-[58%] bottom-[3%] lg:bottom-[6%]",
    animationDelay: 0.6,
  },
  {
    id: "team-7",
    name: "Marcus",
    role: "Design Lead",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-26 h-26 md:w-30 md:h-30 lg:w-36 lg:h-36",
    positionClass: "right-[13%] bottom-[25%] lg:bottom-[30%]",
    animationDelay: 0.7,
  },
  {
    id: "team-8",
    name: "Devon",
    role: "Producer",
    image: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=300&h=300",
    sizeClass: "w-22 h-22 md:w-26 md:h-26 lg:w-32 lg:h-32",
    positionClass: "right-[3%] bottom-[5%] lg:bottom-[9%]",
    animationDelay: 0.8,
  },
];

export const SERVICE_OFFERINGS: ServiceOffering[] = [
  {
    id: "offering-1",
    category: "Office of multiple interest content",
    title: "Collaborative & partnership",
  },
  {
    id: "offering-2",
    category: "The hanger US Air Force digital experimental",
    title: "We talk about our weight",
  },
  {
    id: "offering-3",
    category: "Delta faucet content, social, digital",
    title: "Piloting digital confidence",
    hasCollageBadge: true,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    author: "Arthur Vance",
    role: "VP of Product Development",
    company: "Delta Faucets Group",
    quote: "Elementum delivered the site within the timeline as they requested. In the end, the client found a 50% increase in traffic with in days since its launch. They also had an impressive ability to use technologies that the company hasn't used, which have also proved to be easy to use and reliable.",
    image: "https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=200",
    positionClass: "left-[10%] top-[40%] w-16 h-16 md:w-20 md:h-20 lg:w-26 lg:h-26",
  },
  {
    id: "test-2",
    author: "Sophia Chen",
    role: "Director of UX Innovation",
    company: "Lumina Intelligence",
    quote: "They refuse to play things safe, and that's exactly what we needed to break out of our rigid corporate design habits. They are truly a masterclass studio of strategic thinkers and makers who care about every final pixel.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    positionClass: "right-[15%] top-[15%] w-16 h-16 md:w-20 md:h-20 lg:w-24 lg:h-24",
  },
  {
    id: "test-3",
    author: "Elena Rostova",
    role: "Co-Founder",
    company: "Solis Strategic Design",
    quote: "Working with Elementum has been an absolute game changer. Their creative design thinking refreshed our entire brand architecture, resulting in a 4x increase in inbound inquiries and deep digital adoption.",
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200",
    positionClass: "left-[16%] top-[12%] w-12 h-12 md:w-16 md:h-16 lg:w-20 lg:h-20",
  },
  {
    id: "test-4",
    author: "Jordan Bailey",
    role: "VP of Creative Direction",
    company: "Aero Digital Futures",
    quote: "Their collaborative style felt like a fluid extension of our own core team. They delivered creative solutions that were not only gorgeously customized but deeply backed by cultural and user insights.",
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    positionClass: "right-[12%] top-[42%] w-14 h-14 md:w-18 md:h-18 lg:w-22 lg:h-22",
  },
  {
    id: "test-5",
    author: "Tariq Malik",
    role: "Head of Growth Strategy",
    company: "Nove Labs Corp",
    quote: "The digital confidence we gained after piloting their strategy helped us launch our mobile service to over 100k active users with incredibly seamless retention metrics.",
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200",
    positionClass: "left-[5%] top-[18%] w-10 h-10 md:w-12 md:h-12 lg:w-14 lg:h-14",
  },
  {
    id: "test-6",
    author: "Oliver Sterling",
    role: "Managing Partner",
    company: "Apex Ventures",
    quote: "A breath of fresh air. They listen deeply, managing multiple interest content and translating incredibly complex technical systems into elegant, high-impact storytelling.",
    image: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200",
    positionClass: "right-[26%] top-[25%] w-10 h-10 md:w-12 md:h-12 lg:w-14 lg:h-14",
  },
  {
    id: "test-7",
    author: "Maya Rodriguez",
    role: "Product Manager",
    company: "Faucets & Flow Tech",
    quote: "Unbelievably precise. The entire site was delivered ahead of schedule and feels extremely performant. They have an impressive workflow and they are incredibly collaborative.",
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200",
    positionClass: "left-[6%] bottom-[15%] w-12 h-12 md:w-14 md:h-14 lg:w-16 lg:h-16",
  },
  {
    id: "test-8",
    author: "Devon Brooks",
    role: "Chief Operating Officer",
    company: "Hanger Labs Global",
    quote: "Elementum pushed us to think about tomorrow in every single user flow we co-created. Their social and digital research is second to none.",
    image: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=200",
    positionClass: "right-[8%] bottom-[12%] w-18 h-18 md:w-22 md:h-22 lg:w-28 lg:h-28",
  },
];
